// # Restaurant API

POST http://localhost:3000/api/restaurant
Content-Type: application/json

{
    "name": "Restaurant 2",
    "desc": "Description 2",
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Frestaurant&psig=AOvVaw0QZ2X0Z3Q4Q4Q4Q4Q4Q4Q4&ust=1629789858662000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjQ4ZqHgvICFQAAAAAdAAAAABAD",
    "address": "Address 2",
    "cuisine": "Cousine 2",
    "rating": 4,
    "price_range": 2
}

###

GET http://localhost:3000/api/restaurant

###

GET http://localhost:3000/api/restaurant/654a8919ab17210a549f6e23

###

DELETE http://localhost:3000/api/restaurant/654a8919ab17210a549f6e23

###

PUT http://localhost:3000/api/restaurant/654acf43ac579d6db5029b7e
Content-Type: application/json

{
    "name": "TESTEEEEE2",
    "desc": "Description 2",
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Frestaurant&psig=AOvVaw0QZ2X0Z3Q4Q4Q4Q4Q4Q4Q4&ust=1629789858662000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjQ4ZqHgvICFQAAAAAdAAAAABAD",
    "address": "Address 2",
    "cuisine": "Cousine 2",
    "rating": 4,
    "price_range": 2
}

###

// # User API

POST http://localhost:3000/api/user
Content-Type: application/json

{
    "username": "User 1",
    "email": "teste@gmail.com",
    "password": "123456"
}

###

GET http://localhost:3000/api/user

###

GET http://localhost:3000/api/user/654ad5359f7b7bdeed12dc9e

###

DELETE http://localhost:3000/api/user/654ad5359f7b7bdeed12dc9e

###

PUT http://localhost:3000/api/user/654ad5359f7b7bdeed12dc9e
Content-Type: application/json

{
    "username": "User 1",
    "email": "email.com.br",
    "password": "123456"
}




