// # Restaurant API

POST http://localhost:3000/api/restaurant
Content-Type: application/json

{
    "name": "Restaurant 5",
    "desc": "Description 5",
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Frestaurant&psig=AOvVaw0QZ2X0Z3Q4Q4Q4Q4Q4Q4Q4&ust=1629789858662000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjQ4ZqHgvICFQAAAAAdAAAAABAD",
    "address": "Address 2",
    "cuisine": "Cousine 2",
    "rating": 4,
    "price_range": 2
}

###

GET http://localhost:3000/api/restaurant

###

GET http://localhost:3000/api/restaurant/654a8919ab17210a549f6e23

###

DELETE http://localhost:3000/api/restaurant/654b9025751ca1ffb5d7d061

###

PUT http://localhost:3000/api/restaurant/654acf43ac579d6db5029b7e
Content-Type: application/json

{
    "name": "TESTEEEEE2",
    "desc": "Description 2",
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Frestaurant&psig=AOvVaw0QZ2X0Z3Q4Q4Q4Q4Q4Q4Q4&ust=1629789858662000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjQ4ZqHgvICFQAAAAAdAAAAABAD",
    "address": "Address 2",
    "cuisine": "Cousine 2",
    "rating": 4,
    "price_range": 2
}

###

PUT http://localhost:3000/api/restaurant/add_evaluation/654acf43ac579d6db5029b7e
Content-Type: application/json

{
    "user_id": "654ad5bd9f7b7bdeed12dca7",
    "rating": 2,
    "comment": "Comment 1"
}

###

// # User API

POST http://localhost:3000/api/user
Content-Type: application/json

{
    "username": "User 4",
    "email": "teste4@gmail.com",
    "password": "123456"
}

###

GET http://localhost:3000/api/user

###

GET http://localhost:3000/api/user/654ad5bd9f7b7bdeed12dca7

###

DELETE http://localhost:3000/api/user/654ad5359f7b7bdeed12dc9e

###

PUT http://localhost:3000/api/user/654ad5359f7b7bdeed12dc9e
Content-Type: application/json

{
    "username": "User 1",
    "email": "email.com.br",
    "password": "123456"
}

###

PUT http://localhost:3000/api/user/visited_restaurant/654c212b102addf54dddb086
Content-Type: application/json

{
    "id_restaurant": "654c219c102addf54dddb088"
}

###

// # Evaluation API

POST http://localhost:3000/api/evaluation
Content-Type: application/json

{
    "user_id":"654ad5bd9f7b7bdeed12dca7",
    "restaurant_id":"654af1ba6e7ddac51500678f",
    "rating": 5,
    "comment": "Comment 1",
    "date": "2021-08-24T03:00:00.000Z"
}

###

GET http://localhost:3000/api/evaluation

###

GET http://localhost:3000/api/evaluation/654af09d55aa1c8fbbd5803f

###

DELETE http://localhost:3000/api/evaluation/654af09d55aa1c8fbbd5803f

###

PUT http://localhost:3000/api/evaluation/654af1cb6e7ddac515006795
Content-Type: application/json

{
    "user_id":"654ad5bd9f7b7bdeed12dca7",
    "restaurant_id":"654af1ba6e7ddac51500678f",
    "rating": 2,
    "comment": "TESTE224"
}













