import { getServerSession } from 'next-auth'
import { Inter } from 'next/font/google'

import { Navbar } from '../components'
import './globals.css'
import SessionProvider from '@/utils/SessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout ({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className + ' bg-[#001935] text-white'}>
      <SessionProvider session={session}>
        <div className='mx-auto max-w-5xl text-2xl gap-2 mb-10'>
        <Navbar />
          {children}
        </div>
      </SessionProvider>
      </body>
    </html>
  )
}
